package clo

import (
	"context"
	"fmt"
	"os"
	"strings"
	"testing"

	"github.com/clo-ru/terraform-provider-clo/v2/internal/cloapi"
	"github.com/google/uuid"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/v2/terraform"
)

const (
	serverName = "serv"
)

func TestAccCloInstance_basic(t *testing.T) {
	skipIfNotAcc(t)
	cli, err := getTestClient()
	if err != nil {
		t.Error("Error get test client ", err)
	}
	imageID := getTestImageID(t, cli)

	var server = new(cloapi.Server)

	resource.Test(t, resource.TestCase{
		PreCheck:          func() { testAccCloPreCheck(t) },
		ProviderFactories: testAccProviders,
		CheckDestroy:      testAccCheckInstanceDestroy,
		Steps: []resource.TestStep{
			{
				Config: testAccCloInstanceBasicConf(imageID),
				Check: resource.ComposeTestCheckFunc(
					testAccCheckInstanceExists(fmt.Sprintf("clo_compute_instance.%s", serverName), server),
				),
			},
		},
	})
}

func TestAccCloInstance_withKeypair(t *testing.T) {
	skipIfNotAcc(t)
	cli, err := getTestClient()
	if err != nil {
		t.Error("Error get test client ", err)
	}
	imageID := getTestImageID(t, cli)

	var server = new(cloapi.Server)
	keypair, err := buildTestKeypair(cli, t)
	if err != nil {
		t.Error("Error get test client ", err)
	}

	resource.Test(t, resource.TestCase{
		PreCheck:          func() { testAccCloPreCheck(t) },
		ProviderFactories: testAccProviders,
		CheckDestroy:      testAccCheckInstanceDestroy,
		Steps: []resource.TestStep{
			{
				Config: testAccCloInstanceWithKeypairConf(imageID, keypair),
				Check: resource.ComposeTestCheckFunc(
					testAccCheckInstanceExists(fmt.Sprintf("clo_compute_instance.%s", serverName), server),
				),
			},
		},
	})
}

func testAccCloInstanceWithKeypairConf(imageID, keypair string) string {
	return fmt.Sprintf(
		`resource "clo_compute_instance" "%s" {
  				project_id = "%s"
  				name = "%s"
  				image_id = "%s"
  				flavor_ram = 4
  				flavor_vcpus = 2
  				block_device{
   					size = 10
   					bootable=true
   					storage_type = "volume"
  				}
  				addresses{
   					version = 4
   					external=true
   					ddos_protection=false
  				}
				keypairs = ["%s"]
	}`, serverName, os.Getenv("CLO_API_PROJECT_ID"), serverName, imageID, keypair)
}

func testAccCloInstanceBasicConf(imageID string) string {
	return fmt.Sprintf(
		`resource "clo_compute_instance" "%s" {
  				project_id = "%s"
  				name = "%s"
  				image_id = "%s"
  				flavor_ram = 4
  				flavor_vcpus = 2
  				block_device{
   					size = 10
   					bootable=true
   					storage_type = "volume"
  				}
  				addresses{
   					version = 4
   					external=true
   					ddos_protection=false
  				}
	}`, serverName, os.Getenv("CLO_API_PROJECT_ID"), serverName, imageID)
}

func testAccCheckInstanceExists(n string, serverItem *cloapi.Server) resource.TestCheckFunc {
	return func(state *terraform.State) error {
		rs, ok := state.RootModule().Resources[n]
		if !ok {
			return fmt.Errorf("not found: %s", n)
		}
		if rs.Primary.ID == "" {
			return fmt.Errorf("server with ID is not set")
		}
		cli := testAccProvider.Meta().(*providerMeta).v3
		srv, e := cli.GetServer(context.Background(), rs.Primary.ID)
		if e != nil {
			return e
		}
		*serverItem = *srv
		return nil
	}
}

func testAccCheckInstanceDestroy(st *terraform.State) error {
	cli := testAccProvider.Meta().(*providerMeta).v3
	for _, rs := range st.RootModule().Resources {
		if rs.Type != "clo_compute_instance" {
			continue
		}
		_, e := cli.GetServer(context.Background(), rs.Primary.ID)
		if e == nil {
			return fmt.Errorf("clo instance %s still exists", rs.Primary.ID)
		}
		if cloapi.IsNotFound(e) {
			return nil
		}
		return e
	}
	return nil
}

// TestAccCloInstance_recipeAndKeypair proves the full Phase 1 chain declaratively:
// a keypair generated by the clo_compute_keypair resource and a recipe resolved by
// name through the clo_project_recipe data source are both wired into an instance.
func TestAccCloInstance_recipeAndKeypair(t *testing.T) {
	skipIfNotAcc(t)
	cli, err := getTestClient()
	if err != nil {
		t.Fatalf("get test client: %v", err)
	}
	recipe, imageID := getTestRecipe(t, cli)
	keyName := "e2e-chain-" + strings.ReplaceAll(uuid.NewString(), "-", "")

	server := new(cloapi.Server)
	instanceAddr := fmt.Sprintf("clo_compute_instance.%s", serverName)

	resource.Test(t, resource.TestCase{
		PreCheck:          func() { testAccCloPreCheck(t) },
		ProviderFactories: testAccProviders,
		CheckDestroy:      testAccCheckInstanceDestroy,
		Steps: []resource.TestStep{
			{
				Config: testAccCloInstanceRecipeKeypairConf(recipe, imageID, keyName),
				Check: resource.ComposeTestCheckFunc(
					testAccCheckInstanceExists(instanceAddr, server),
					// the data source resolved the recipe id ...
					resource.TestCheckResourceAttrSet("data.clo_project_recipe.chain", "recipe_id"),
					// ... and the instance received exactly that id
					resource.TestCheckResourceAttrPair(instanceAddr, "recipe_id", "data.clo_project_recipe.chain", "recipe_id"),
					// the generated keypair yielded a private key and is attached to the instance
					resource.TestCheckResourceAttrSet("clo_compute_keypair.chain", "private_key"),
					resource.TestCheckResourceAttr(instanceAddr, "keypairs.#", "1"),
				),
			},
		},
	})
}

func testAccCloInstanceRecipeKeypairConf(recipe cloapi.Recipe, imageID, keyName string) string {
	proj := os.Getenv("CLO_API_PROJECT_ID")
	// meet the recipe's flavor minimums, but never go below the known-good defaults.
	ram := atLeast(4, recipe.MinRam)
	vcpus := atLeast(2, recipe.MinVcpus)
	size := atLeast(10, recipe.MinDisk)
	return fmt.Sprintf(`
resource "clo_compute_keypair" "chain" {
  project_id = "%s"
  name       = "%s"
}

data "clo_project_recipe" "chain" {
  project_id = "%s"
  name       = "%s"
}

resource "clo_compute_instance" "%s" {
  project_id   = "%s"
  name         = "%s"
  image_id     = "%s"
  flavor_ram   = %d
  flavor_vcpus = %d
  recipe_id    = data.clo_project_recipe.chain.recipe_id
  keypairs     = [clo_compute_keypair.chain.id]
  block_device {
    size         = %d
    bootable     = true
    storage_type = "volume"
  }
  addresses {
    version         = 4
    external        = true
    ddos_protection = false
  }
}`, proj, keyName, proj, recipe.Name, serverName, proj, serverName, imageID, ram, vcpus, size)
}

// atLeast returns the larger of def and min, so the instance flavor satisfies the
// recipe's minimum without dropping below a known-good default.
func atLeast(def, min int) int {
	if min > def {
		return min
	}
	return def
}
