package clo

import (
	"context"

	"github.com/clo-ru/terraform-provider-clo/v2/internal/cloapi"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func resourceKeypair() *schema.Resource {
	return &schema.Resource{
		Description: "Manage an SSH keypair in the project. Provide `public_key` to import an " +
			"existing key, or omit it to have the API generate one (the generated `private_key` is " +
			"returned only once and stored in state).",
		ReadContext:   resourceKeypairRead,
		CreateContext: resourceKeypairCreate,
		DeleteContext: resourceKeypairDelete,
		Schema: map[string]*schema.Schema{
			"project_id": {
				Description: "ID of the project where the keypair should be created",
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
			},
			"name": {
				Description: "Human-readable name of the keypair",
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
			},
			"public_key": {
				Description: "Public key to import. If omitted, a new keypair is generated by the API.",
				Type:        schema.TypeString,
				Optional:    true,
				Computed:    true,
				ForceNew:    true,
			},
			"private_key": {
				Description: "Private key of a generated keypair. Only set when `public_key` was not provided.",
				Type:        schema.TypeString,
				Computed:    true,
				Sensitive:   true,
			},
			"id": {
				Description: "ID of the keypair",
				Type:        schema.TypeString, Computed: true},
			"created_in": {
				Description: "Timestamp the keypair was created",
				Type:        schema.TypeString, Computed: true},
		},
	}
}

func resourceKeypairCreate(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	cli := m.(*providerMeta).v3
	projectID := d.Get("project_id").(string)
	name := d.Get("name").(string)
	if pk, ok := d.GetOk("public_key"); ok {
		id, err := cli.ImportKeypair(ctx, projectID, name, pk.(string))
		if err != nil {
			return diag.FromErr(err)
		}
		d.SetId(id)
		return resourceKeypairRead(ctx, d, m)
	}
	kp, err := cli.GenerateKeypair(ctx, projectID, name)
	if err != nil {
		return diag.FromErr(err)
	}
	if e := d.Set("private_key", kp.PrivateKey); e != nil {
		return diag.FromErr(e)
	}
	d.SetId(kp.ID)
	return resourceKeypairRead(ctx, d, m)
}

func resourceKeypairRead(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	cli := m.(*providerMeta).v3
	kp, err := cli.GetKeypair(ctx, d.Id())
	if cloapi.IsNotFound(err) {
		d.SetId("")
		return nil
	}
	if err != nil {
		return diag.FromErr(err)
	}
	fields := map[string]interface{}{
		"id":         kp.ID,
		"name":       kp.Name,
		"public_key": kp.PublicKey,
		"created_in": kp.CreatedIn,
	}
	for k, v := range fields {
		if e := d.Set(k, v); e != nil {
			return diag.FromErr(e)
		}
	}
	return nil
}

func resourceKeypairDelete(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	cli := m.(*providerMeta).v3
	if err := cli.DeleteKeypair(ctx, d.Id()); err != nil {
		return diag.FromErr(err)
	}
	return nil
}
