package cloapi

import (
	"context"
	"errors"
	"time"

	gen "github.com/clo-ru/cloapi-go-client/v3"
)

// Keypair is the provider-facing view of an SSH keypair. PrivateKey is only set
// when the keypair was generated by the API; Import never returns a private key.
type Keypair struct {
	ID         string
	Name       string
	PublicKey  string
	PrivateKey string
	CreatedIn  string
}

func keypairFromSchema(r *gen.KeyPairSchema) Keypair {
	return Keypair{
		ID:        r.Id,
		Name:      r.Name,
		PublicKey: r.PublicKey,
		CreatedIn: r.CreatedIn.Format(time.RFC3339),
	}
}

// ImportKeypair imports an existing public key and returns the keypair ID.
func (c *Client) ImportKeypair(ctx context.Context, projectID, name, publicKey string) (string, error) {
	resp, err := c.gen.ImportKeypairWithResponse(ctx, projectID, gen.ImportKeypairJSONRequestBody{
		Name:      name,
		PublicKey: publicKey,
	})
	if err != nil {
		return "", err
	}
	if resp.OK == nil || resp.OK.Result == nil {
		return "", errors.New("cloapi: empty keypair import response")
	}
	return resp.OK.Result.Id, nil
}

// GenerateKeypair asks the API to generate a new keypair and returns it,
// including the one-time private key (available only on this response).
func (c *Client) GenerateKeypair(ctx context.Context, projectID, name string) (*Keypair, error) {
	resp, err := c.gen.GenerateKeypairWithResponse(ctx, projectID, gen.GenerateKeypairJSONRequestBody{Name: name})
	if err != nil {
		return nil, err
	}
	if resp.OK == nil || resp.OK.Result == nil {
		return nil, errors.New("cloapi: empty keypair generate response")
	}
	r := resp.OK.Result
	return &Keypair{
		ID:         r.Id,
		Name:       name, // generate result carries no name; echo the requested one
		PublicKey:  r.PublicKey,
		PrivateKey: r.PrivateKey,
		CreatedIn:  r.CreatedIn.Format(time.RFC3339),
	}, nil
}

// GetKeypair returns the keypair's current detail.
func (c *Client) GetKeypair(ctx context.Context, id string) (*Keypair, error) {
	resp, err := c.gen.KeypairDetailWithResponse(ctx, id)
	if err != nil {
		return nil, err
	}
	if resp.OK == nil || resp.OK.Result == nil {
		return nil, errors.New("cloapi: empty keypair detail response")
	}
	k := keypairFromSchema(resp.OK.Result)
	return &k, nil
}

// ListKeypairs returns the project's keypairs (single page, matching the other list adapters).
func (c *Client) ListKeypairs(ctx context.Context, projectID string) ([]Keypair, error) {
	resp, err := c.gen.KeyPairsListWithResponse(ctx, projectID)
	if err != nil {
		return nil, err
	}
	if resp.OK == nil || resp.OK.Result == nil {
		return nil, nil
	}
	items := *resp.OK.Result
	out := make([]Keypair, 0, len(items))
	for i := range items {
		out = append(out, keypairFromSchema(&items[i]))
	}
	return out, nil
}

// DeleteKeypair deletes a keypair.
func (c *Client) DeleteKeypair(ctx context.Context, id string) error {
	_, err := c.gen.KeypairDeleteWithResponse(ctx, id)
	return err
}
